// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAucCepm-3AYYmB23DhzvXK5Kf0nOZev24',
    appId: '1:60557841684:web:3e2867ac435bc4e5195e01',
    messagingSenderId: '60557841684',
    projectId: 'crud-8aa32',
    authDomain: 'crud-8aa32.firebaseapp.com',
    storageBucket: 'crud-8aa32.firebasestorage.app',
    measurementId: 'G-N447GYRGW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD9rvW5p8FLL55QhvVL3XHAV_AwVwR_jA',
    appId: '1:60557841684:android:49efbc7ba4381fe1195e01',
    messagingSenderId: '60557841684',
    projectId: 'crud-8aa32',
    storageBucket: 'crud-8aa32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4MHwHiJa0HFJWaZ8FARBAFYLWZBu4LcI',
    appId: '1:60557841684:ios:af0e2e7068bc3834195e01',
    messagingSenderId: '60557841684',
    projectId: 'crud-8aa32',
    storageBucket: 'crud-8aa32.firebasestorage.app',
    iosBundleId: 'com.example.contacts.contactsCrudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4MHwHiJa0HFJWaZ8FARBAFYLWZBu4LcI',
    appId: '1:60557841684:ios:af0e2e7068bc3834195e01',
    messagingSenderId: '60557841684',
    projectId: 'crud-8aa32',
    storageBucket: 'crud-8aa32.firebasestorage.app',
    iosBundleId: 'com.example.contacts.contactsCrudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAucCepm-3AYYmB23DhzvXK5Kf0nOZev24',
    appId: '1:60557841684:web:1cda67b634840df7195e01',
    messagingSenderId: '60557841684',
    projectId: 'crud-8aa32',
    authDomain: 'crud-8aa32.firebaseapp.com',
    storageBucket: 'crud-8aa32.firebasestorage.app',
    measurementId: 'G-T4V91CV8W1',
  );

}